### PR TITLE
Allow passthrough handlers

### PR DESCRIPTION
**Pull request by ksrb**
Still trying to understand parts of the code but this PR allows you to do the following:

```js
const server = new QueryParamAwarePretender();
server.post('/screenshot', server.passthrough);
```

Also need to write some test.

### CODE REVIEW

**Comment by hjdivad** [comment]
@ksrb What are the intended semantics you're going for here?  Is it something like: if the mocked URL does not contain `?` (i.e. has no `search` section at all) then treat that as a passthrough option with normal pretender semantics?

**Comment by hjdivad** [comment]
@ksrb would your needs be met by #6?

**Comment by ksrb** [comment]
I don't thing #6 would help with this I'm trying to add the capability to allow for request to be passed through the pretender regardless of whether or not the URL has a `search` section.

This is necessary for some internal tooling that my team is using but is also a feature pretender has that no longer works when using this project see https://github.com/pretenderjs/pretender#pass-through and https://github.com/rwjblue/pretender-query-param-handler/issues/3.

**Comment by hjdivad** [comment]
Okay having discussed this offline I see that I was mistaken in how I imagined passthroughs were handled, given the special handling you pointed out.

It looks like `FakeXHR` [defers this to pretender](https://github.com/pretenderjs/pretender/blob/65fbf0a608f2e4b4fd79657a77a41f52077074a9/src/interceptor.ts#L23-L27) so we should be able to add support for passthroughs by overriding [checkPassthrough](https://github.com/pretenderjs/pretender/blob/65fbf0a608f2e4b4fd79657a77a41f52077074a9/src/pretender.ts#L189-L202) with a query-param aware implementation.

**Comment by hjdivad** [comment]
So the next steps forward for landing this are

1. Write a test here that mocks a path with two different sets of query params, one of which is mocked and one of which is passthrough. Have the passthrough one load a text file in `public` or something similar.  Confirm it fails in the expected way.

2. Fix the test by overriding [checkPassthrough](https://github.com/pretenderjs/pretender/blob/65fbf0a608f2e4b4fd79657a77a41f52077074a9/src/pretender.ts#L189-L202) with a function that looks up the QP-handler and `return true` if that handler is `server.passthrough`

**Pull request closed without merging**
